/**
 * @file Listen.actions.ts
 * Defines state change actions for listen pages.
 */

export enum ListenActionTypes {
  'LISTEN_VIEW_PODCAST' = '[Listen] VIEW_PODCAST',
  'LISTEN_VIEW_EPISODE' = '[Listen] VIEW_EPISODE',

  'LISTEN_PLAYER_SHOW_CLOSED_CAPTIONS_DIALOG' = '[Listen] PLAYER_SHOW_CLOSED_CAPTIONS_DIALOG',
  'LISTEN_PLAYER_HIDE_CLOSED_CAPTIONS_DIALOG' = '[Listen] PLAYER_HIDE_CLOSED_CAPTIONS_DIALOG',
  'LISTEN_PLAYER_TOGGLE_CLOSED_CAPTIONS_DIALOG_SHOWN' = '[Listen] PLAYER_TOGGLE_CLOSED_CAPTIONS_DIALOG_SHOWN',
  'LISTEN_PODCAST_SHOW_SHARE_DIALOG' = '[Listen] PODCAST_SHOW_SHARE_DIALOG',
  'LISTEN_PODCAST_HIDE_SHARE_DIALOG' = '[Listen] PODCAST_HIDE_SHARE_DIALOG',
  'LISTEN_PODCAST_TOGGLE_SHARE_DIALOG_SHOWN' = '[Listen] PODCAST_TOGGLE_SHARE_DIALOG_SHOWN',
  'LISTEN_PODCAST_SHOW_FOLLOW_DIALOG' = '[Listen] PODCAST_SHOW_FOLLOW_DIALOG',
  'LISTEN_PODCAST_HIDE_FOLLOW_DIALOG' = '[Listen] PODCAST_HIDE_FOLLOW_DIALOG',
  'LISTEN_PODCAST_TOGGLE_FOLLOW_DIALOG_SHOWN' = '[Listen] PODCAST_TOGGLE_FOLLOW_DIALOG_SHOWN',
  'LISTEN_PODCAST_SHOW_SUPPORT_DIALOG' = '[Listen] PODCAST_SHOW_SUPPORT_DIALOG',
  'LISTEN_PODCAST_HIDE_SUPPORT_DIALOG' = '[Listen] PODCAST_HIDE_SUPPORT_DIALOG',
  'LISTEN_PODCAST_TOGGLE_SUPPORT_DIALOG_SHOWN' = '[Listen] PODCAST_TOGGLE_SUPPORT_DIALOG_SHOWN',

  'LISTEN_EPISODE_SHOW_SHARE_DIALOG' = '[Listen] EPISODE_SHOW_SHARE_DIALOG',
  'LISTEN_EPISODE_HIDE_SHARE_DIALOG' = '[Listen] EPISODE_HIDE_SHARE_DIALOG',
  'LISTEN_EPISODE_TOGGLE_SHARE_DIALOG_SHOWN' = '[Listen] EPISODE_TOGGLE_SHARE_DIALOG_SHOWN'
}

export type ListenAction = {
  type: ListenActionTypes;
  payload?: any;
};
