import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '@styles/Home.module.scss';
import PrxLogo from '@svg/prx-logo.svg';

const Home: NextPage = () => (
  <div className={styles.container}>
    <Head>
      <title>PRX Play</title>
      <meta name="description" content="Generated by create next app" />
    </Head>

    <main className={styles.main}>
      <PrxLogo className={styles.logo} />
      <h1 className={styles.title}>
        <span>P</span>
        <span>l</span>
        <span>a</span>
        <span>y</span>
      </h1>
    </main>
  </div>
);

export default Home;
